sudo: required
services:
  - docker

before_install:
  - docker build -t nqthai95/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nqthai95/react-test npm run test

after_success: # build production image 
  - docker build -t nqthai95/multi-client-sample ./client
  - docker build -t nqthai95/multi-nginx-sample ./nginx
  - docker build -t nqthai95/multi-server-sample ./server
  - docker build -t nqthai95/multi-worker-sample ./worker
#Login into docker cli
# add username password to travis env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push to docker hub
  - docker push nqthai95/multi-client-sample
  - docker push nqthai95/multi-nginx-sample
  - docker push nqthai95/multi-server-sample
  - docker push nqthai95/multi-worker-sample
deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  environment: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-433126474652
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY